---
# See the following link(s) for pre-commit help: https://pre-commit.com/

repos:
  # See the following link for pre-commit-hooks help: https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
      - id: no-commit-to-branch
  # See the following link for pre-commit-terraform help: https://github.com/antonbabenko/pre-commit-terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--module
